# Generated by Django 5.2.17 on 2026-08-31 23:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('sequence_number', models.PositiveIntegerField(unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_class', models.CharField(choices=[('STOCK', 'Stock'), ('BOND', 'Bond')], max_length=10)),
                ('target_percent', models.PositiveSmallIntegerField(help_text='Target percentage of the vaporFUND portfolio.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enabled', models.BooleanField(default=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Annual expense ratio expressed as a percentage.', max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'ETF',
                'verbose_name_plural': 'ETFs',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Purchase'), ('DIVIDEND', 'Dividend'), ('ADJUSTMENT', 'Adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Deposits and dividends are positive; purchases are negative.', max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transaction', to='portfolio.contribution')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('HOLD_CASH', 'Hold cash')], max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLIANCE_APPROVED', 'Compliance approved'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('available_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('portfolio_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_shortfall', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('price_date', models.DateField()),
                ('shares', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation', to='portfolio.contribution')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='portfolio.etf')),
            ],
            options={
                'ordering': ['-contribution__date'],
            },
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('shares', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=6, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('broker_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trade_execution', to='portfolio.cashtransaction')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_executions', to='portfolio.etf')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='portfolio.recommendation')),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoldingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('shares_acquired', models.PositiveIntegerField()),
                ('shares_remaining', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=6, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compliance_eligible_date', models.DateField(help_text='Earliest system-calculated date for a possible sale. Employer compliance approval still takes precedence.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holding_lots', to='portfolio.etf')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='holding_lot', to='portfolio.tradeexecution')),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=6, help_text='Unadjusted closing price used for whole-share purchases.', max_digits=14)),
                ('adjusted_close', models.DecimalField(decimal_places=6, help_text='Adjusted close used for total-return analysis.', max_digits=14)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.etf')),
            ],
            options={
                'verbose_name': 'Price history',
                'verbose_name_plural': 'Price history',
                'ordering': ['etf__ticker', '-date'],
                'constraints': [models.UniqueConstraint(fields=('etf', 'date'), name='unique_etf_price_date')],
            },
        ),
    ]
