# Generated by Django 5.2.17 on 2026-09-03 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-contribution__date', 'plan_order']},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='plan_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='portfolio.contribution'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('contribution', 'plan_order'), name='unique_recommendation_plan_order'),
        ),
    ]
