# Generated by Django 5.2.17 on 2026-09-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_populate_default_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='sequence_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_contribution_date_per_account'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('account', 'sequence_number'), name='unique_contribution_sequence_per_account'),
        ),
    ]
