# Generated by Django 5.2.17 on 2026-09-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_contribution_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateField(),
        ),
    ]
