# Generated by Django 5.2.17 on 2026-09-13 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contribution_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='portfolio.account')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_targets', to='portfolio.etf')),
            ],
            options={
                'ordering': ['account__name', 'etf__ticker'],
                'constraints': [models.UniqueConstraint(fields=('account', 'etf'), name='unique_account_etf_target')],
            },
        ),
    ]
