# Generated by Django 5.2.17 on 2026-09-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_accounttarget'),
    ]

    operations = [
    ]


from django.db import migrations


DEFAULT_ACCOUNT_NAME = "vaporFUND Test"


def populate_account_targets(apps, schema_editor):
    Account = apps.get_model("portfolio", "Account")
    AccountTarget = apps.get_model(
        "portfolio",
        "AccountTarget",
    )
    ETF = apps.get_model("portfolio", "ETF")

    account = Account.objects.get(
        name=DEFAULT_ACCOUNT_NAME
    )

    for etf in ETF.objects.all():
        AccountTarget.objects.update_or_create(
            account=account,
            etf=etf,
            defaults={
                "target_percent": etf.target_percent,
            },
        )


def reverse_populate_account_targets(
    apps,
    schema_editor,
):
    Account = apps.get_model("portfolio", "Account")
    AccountTarget = apps.get_model(
        "portfolio",
        "AccountTarget",
    )

    try:
        account = Account.objects.get(
            name=DEFAULT_ACCOUNT_NAME
        )
    except Account.DoesNotExist:
        return

    AccountTarget.objects.filter(
        account=account
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0007_accounttarget",
        ),
    ]

    operations = [
        migrations.RunPython(
            populate_account_targets,
            reverse_populate_account_targets,
        ),
    ]
