# Generated by Django 5.2.17 on 2026-09-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_populate_account_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='target_percent',
        ),
    ]
